#校验库是oracle，启用该配置文件
logging:
    config: classpath:config/logback-prod.xml

server:
    port: 8083
    context-path: /derivation
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: qc
    password: qc
    driver-class-name: oracle.jdbc.driver.OracleDriver
    #druid DataSource配置
    #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
    #1) Destroy线程会检测连接的间隔时间2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
    timeBetweenEvictionRunsMillis: 1000000
    validationQuery: select 1 from dual
    #	是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
    poolPreparedStatements: true
    #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
    maxOpenPreparedStatements: 100
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #	初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
    initialSize: 3
    #最大连接池数量
    maxActive: 20
    #最小连接池数量
    minIdle: 5
    #最大等待时间
    maxWait: 60000
    #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：
    #监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall
    filters: wall,stat




hdfs:
  url: hdfs://192.168.1.87:8020/apps/hive/warehouse/qc.db/
